### ISSUE TITLE
Marshal returns a string

### ISSUE THREAD

**Issue by manicar2093** [quagmt/udecimal#20]
Hi! 

Thanks for make this library! I've been using it and it is great! I just have a doubt.

When marshaling data to JSON this is returned as a string and I don't know if it's better to handle decimal numbers as strings or why this marshaling is happening in this way 😮

**Comment by quagmt** [comment]
Hi, 
Marshaling JSON to a string is preferable for high-precision decimals to avoid precision loss during unmarshaling (you can check [this SO question](https://stackoverflow.com/questions/35709595/why-would-you-use-a-string-in-json-to-represent-a-decimal-number). I believe this is the default behavior for most decimal libraries

**Comment by manicar2093** [comment]
!> Hi, Marshaling JSON to a string is preferable for high-precision decimals to avoid precision loss during unmarshaling (you can check [this SO question](https://stackoverflow.com/questions/35709595/why-would-you-use-a-string-in-json-to-represent-a-decimal-number). I believe this is the default behavior for most decimal libraries

Wow! Thank you. That make sense to me!
